# container image
container_image = docker://quay.io/biocontainers/bowtie:1.3.1--py312hf8dbd9f_10
#container_image = docker://quay.io/biocontainers/bowtie2:2.5.4--he96a11b_6

# script to use
executable = 02-index_ref.sh

# variables
#ref=Bacillus168
staging=/staging/$(netid)/$(project)/

arguments = $(staging) $(ref)

# logs
log = logs/index_$(ref)_$(cluster).$(process).log
error = logs/index_$(ref)_$(cluster).$(process).err
output = logs/index_$(ref)_$(cluster).$(process).out

# transfer files for inputs and outputs

requirements = (HasCHTCStaging == true) && (OpSysMajorVer > 7) && (HasChtcProjects == true)

# resources
request_cpus = 4
request_memory = 4GB
request_disk = 10GB      

queue
