# container image
container_image = docker://quay.io/biocontainers/bedtools:2.27.1--h077b44d_9

# script to use
executable = 07-count-insertions-per-TA-sites.sh

# variables
staging=/staging/$(netid)/$(project)/
ref=Bacillus168

arguments = $(sample) $(ref) $(staging) $(request_cpus)

# logs
log = logs/InsertionsPerTASites_$(sample)_$(cluster).$(process).log
error = logs/InsertionsPerTASites_$(sample)_$(cluster).$(process).err
output = logs/InsertionsPerTASites_$(sample)_$(cluster).$(process).out

# transfer files for inputs and outputs
transfer_input_files = file://$(staging)/insertions/$(sample)_insertions.bed, file://$(staging)/insertions/$(ref)_TA_sites.bed
transfer_output_files = $(sample)_insertion_counts.bed
transfer_output_remaps = "$(sample)_insertion_counts.bed=file://$(staging)/insertions/$(sample)_insertions_counts.bed"

requirements = (HasCHTCStaging == true) && (OpSysMajorVer > 7) && (HasChtcProjects == true)

# resources
request_cpus = 8
request_memory = 32GB
request_disk = 16GB      

queue
